# Generated by Django 4.2 on 2023-06-23 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='user_id',
        ),
    ]
